✨ feat : Delivery Manager CRUD 구현
Sparta-Phoenix/logistics-platform pull request #22
Opened 2024-12-11 21:46 UTC by hiimsajo

## Subject
> 배송담당자 CRUD 구현

## Content
> 서비스와 컨트롤러에 crud를 추가했습니다.
> repository와 repository custom 내용을 추가했습니다.
> 엔티티에 수정, 삭제 메서드를 추가했습니다.

2024-12-12 02:51 UTC, drinkgalaxy approved these changes
querydsl 적용하시다니 멋지십니다! 너무 고생 많으셨어요! 그리고 잠도 푹 자면서 하세요 ㅎㅎ 무리 금지!!!

2024-12-12 02:51 UTC, drinkgalaxy commented on delivery-manager-service/src/main/java/com/logistics/platform/deliverymanagerservice/application/service/DeliveryManagerService.java
> +  public DeliveryManagerResponseDto updateDeliveryManager(UUID deliveryManagerId, DeliveryManagerUpdateRequestDto deliveryManagerUpdateRequestDto){
사소하지만.. update 할 때도 @Transactional 거는 거 어떠신가요?

2024-12-12 02:51 UTC, drinkgalaxy commented on delivery-manager-service/src/main/java/com/logistics/platform/deliverymanagerservice/domain/model/DeliveryManager.java
> +
Boolean 의 기본값은 null 이라 isDeleted = false 를 명시해줘야하는 걸로... 알고있습니다! (아마도..)

2024-12-12 03:13 UTC, hiimsajo commented on delivery-manager-service/src/main/java/com/logistics/platform/deliverymanagerservice/application/service/DeliveryManagerService.java
> +  public DeliveryManagerResponseDto updateDeliveryManager(UUID deliveryManagerId, DeliveryManagerUpdateRequestDto deliveryManagerUpdateRequestDto){
허걱 감사합니다! 전혀 사소하지 않습니다!

> 사소하지만.. update 할 때도 @transactional 거는 거 어떠신가요?

허걱 감사합니다! 전혀 사소하지 않습니다!

2024-12-12 03:14 UTC, hiimsajo commented on delivery-manager-service/src/main/java/com/logistics/platform/deliverymanagerservice/domain/model/DeliveryManager.java
> +
> Boolean 의 기본값은 null 이라 isDeleted = false 를 명시해줘야하는 걸로... 알고있습니다! (아마도..)

감사합니다! 수정하겠습니다!

2024-12-12 08:38 UTC, Yuurim98 commented on delivery-manager-service/src/main/java/com/logistics/platform/deliverymanagerservice/domain/model/DeliveryManager.java
> +  private DeliveryType deliveryType;
PR 올려주신 거에 해당 enum 클래스는 보이지 않는 것 같은데 제가 못 찾는 건지 혹시 확인해주실 수 있나요?!

2024-12-12 08:39 UTC, Yuurim98 commented on delivery-manager-service/src/main/java/com/logistics/platform/deliverymanagerservice/application/service/DeliveryManagerService.java
> +        .deliveryType(deliveryManagerRequestDto.getDeliveryType())
DeliveryType이 유효하지 않은 형식은 아닌지 검증되면 좋을 것 같습니다!

2024-12-12 08:51 UTC, Yuurim98 commented on delivery-manager-service/src/main/java/com/logistics/platform/deliverymanagerservice/domain/model/DeliveryManager.java
> +public class DeliveryManager extends AuditingFields {
BaseEntity를 상속받는 것 같은데 해당 파일도 확인되지 않는 것 같아서 확인 부탁드립니다!

2024-12-12 08:52 UTC, Yuurim98 approved these changes
코멘트 확인 부탁드립니다! 늦게까지 고생 많으셨어요 ㅜㅜ!

2024-12-12 10:44 UTC, hiimsajo commented on delivery-manager-service/src/main/java/com/logistics/platform/deliverymanagerservice/domain/model/DeliveryManager.java
> +  private DeliveryType deliveryType;
> PR 올려주신 거에 해당 enum 클래스는 보이지 않는 것 같은데 제가 못 찾는 건지 혹시 확인해주실 수 있나요?!

허걱 안올라간게 맞습니다..! 감사합니다! 얼른 수정반영하고 파일도 같이 올리겠습니다!

2024-12-12 10:44 UTC, hiimsajo commented on delivery-manager-service/src/main/java/com/logistics/platform/deliverymanagerservice/application/service/DeliveryManagerService.java
> +        .deliveryType(deliveryManagerRequestDto.getDeliveryType())
오 맞네요~! 감사합니다!

2024-12-12 10:44 UTC, hiimsajo commented on delivery-manager-service/src/main/java/com/logistics/platform/deliverymanagerservice/domain/model/DeliveryManager.java
> +public class DeliveryManager extends AuditingFields {
> BaseEntity를 상속받는 것 같은데 해당 파일도 확인되지 않는 것 같아서 확인 부탁드립니다!

이것도 꼭 올리도록 하겠습니다!

2024-12-12 14:37 UTC, k-jaehyun requested changes
resource 파일 등 프로젝트 실행에 필요한 파일들이 빠져있습니다! 확인 부탁드려요~

2024-12-12 14:46 UTC, k-jaehyun commented on delivery-manager-service/src/main/java/com/logistics/platform/deliverymanagerservice/domain/model/DeliveryManager.java
> +  }
아하 이렇게 구현하셨군요! 👍👍

2024-12-12 14:50 UTC, k-jaehyun commented on delivery-manager-service/src/main/java/com/logistics/platform/deliverymanagerservice/presentation/request/DeliveryManagerUpdateRequestDto.java
> +public class DeliveryManagerUpdateRequestDto {
DeliveryManagerRequestDto 와 필드가 동일 한 것 같은데 혹시 따로 의도하신바가 있으실까요?

2024-12-12 20:37 UTC, hiimsajo commented
> resources 파일 등 프로젝트 실행에 필요한 파일들이 빠져있습니다! 확인 부탁드려요~
> 
> 구현 이후에 커밋하셨을까요?? 구현 순서가 특이하셔서요..!!ㅋㅋㅋ 제 경우에는 기능 구현 -> 테스트 -> 커밋 이후에 다시 기능 구현 -> 테스트 -> 커밋 순서로 작업한답니다!
> 
> 이러면 뭔가 꼬였을 때 롤백하기도 좋고 구현하면서 테스트 하기도 좋더라구요~

오 재현님의 구현 순서 참고해서 해보도록 하겠습니다!! 감사합니다~!

2024-12-12 20:40 UTC, hiimsajo commented on delivery-manager-service/src/main/java/com/logistics/platform/deliverymanagerservice/presentation/request/DeliveryManagerUpdateRequestDto.java
> +public class DeliveryManagerUpdateRequestDto {
처음에는 수정가능한 필드들이 다른가 싶어서 일단 분리를 시켜서 만들어본 것인데, 재현님의 말씀처럼 똑같아서 굳이 따로 둘 필요가 없는 것 같습니다...! 이것도 하나로 두고 쓰는 것으로 수정하도록 하겠습니다! 감사합니다!!

2024-12-13 01:37 UTC, k-jaehyun approved these changes
LGTM!👍👍

2024-12-13 01:37 UTC, k-jaehyun commented on delivery-manager-service/src/main/java/com/logistics/platform/deliverymanagerservice/application/service/DeliveryManagerService.java
> +  }
보통 이런 메서드는 맨 밑으로 빼더라구요! 참고만..!!

2024-12-13 01:43 UTC, hiimsajo commented on delivery-manager-service/src/main/java/com/logistics/platform/deliverymanagerservice/application/service/DeliveryManagerService.java
> +  }
허걱 감사합니다! 참고해서 밑으로 옮기고 머지하겠습니다!!👍

2024-12-13 02:00 UTC, merged